CREATE TABLE raw_data.runs_raw (
    activity_id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    activity_type        TEXT,
    date_of_activity     TIMESTAMP,
    title                TEXT,
    distance             NUMERIC(10,2),
    calories             INTEGER,
    avg_hr               INTEGER,
    max_hr               INTEGER,
    avg_run_cadence      INTEGER,
    avg_pace             NUMERIC(10,2),
    total_ascent         INTEGER,
    total_descent        INTEGER,
    avg_stride_length    NUMERIC(5,2),
    steps                INTEGER,
    moving_time_minutes  NUMERIC,
    elapsed_time_minutes NUMERIC,
    source_file          TEXT,
    record_hash          TEXT UNIQUE,
    loaded_at            TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
